#!/usr/bin/env python3
"""Generate black-box SFT distillation data with Qwen3-1.7B.

The source file is the existing miniLLM conversation JSONL.  For rows selected
for distillation, every assistant turn is regenerated by the teacher while the
original system/user context is retained.  The output remains compatible with
``dataset.sft_dataset.SFTDataset`` and can therefore be trained directly with
``trainer/train_sft.py``.

The script deliberately performs *sequence-level* (black-box) distillation.
Qwen and miniLLM do not share a tokenizer, so Qwen logits must not be used for
token-level KL distillation.

Example:

    python scripts/generate_distill_data.py \
        --input-path dataset/sft/sft.jsonl \
        --output-path dataset/distill/qwen3_1_7b_sft.jsonl \
        --model-path Qwen/Qwen3-1.7B \
        --distill-ratio 0.7 \
        --thinking-ratio 0.15 \
        --batch-size 4

The default 0.7 distill ratio produces one mixed row for every source row:
70% of ordinary conversations receive teacher answers, while 30% retain their
original answers as replay data.  Tool trajectories are also retained by
default because regenerating a tool call without regenerating the subsequent
tool result can create an inconsistent trajectory.
"""

from __future__ import annotations

import argparse
import hashlib
import itertools
import json
import os
import random
import re
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable, Iterator, Mapping, Sequence


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = PROJECT_ROOT / "dataset" / "sft" / "sft.jsonl"
DEFAULT_OUTPUT = (
    PROJECT_ROOT / "dataset" / "distill" / "qwen3_1_7b_sft.jsonl"
)
ALLOWED_ROLES = {"system", "user", "assistant", "tool"}
QWEN_SPECIAL_TOKENS = (
    "<|im_start|>",
    "<|im_end|>",
    "<|endoftext|>",
)


def project_path(path: Path) -> Path:
    """Resolve relative paths against the project root."""

    path = path.expanduser()
    return path.resolve() if path.is_absolute() else (PROJECT_ROOT / path).resolve()


def stable_probability(seed: int, row_index: int, namespace: str) -> float:
    """Return a resume-safe deterministic pseudo-random value in ``[0, 1)``."""

    payload = f"{seed}:{row_index}:{namespace}".encode("utf-8")
    value = int.from_bytes(hashlib.blake2b(payload, digest_size=8).digest(), "big")
    return value / 2**64


def parse_jsonish(value: Any, field_name: str) -> Any:
    """Decode JSON stored as a string while leaving native values unchanged."""

    if not isinstance(value, str):
        return value
    stripped = value.strip()
    if not stripped:
        return None
    try:
        return json.loads(stripped)
    except json.JSONDecodeError as exc:
        raise ValueError(f"invalid JSON in {field_name}: {exc}") from exc


def normalize_messages(raw_messages: Any) -> list[dict[str, Any]]:
    """Validate source messages without importing the training-time dataset."""

    if not isinstance(raw_messages, list) or not raw_messages:
        raise ValueError("'conversations' must be a non-empty list")
    messages: list[dict[str, Any]] = []
    for message_index, raw_message in enumerate(raw_messages):
        if not isinstance(raw_message, Mapping):
            raise TypeError(f"message {message_index} must be an object")
        role = raw_message.get("role")
        if role not in ALLOWED_ROLES:
            raise ValueError(
                f"message {message_index} has unsupported role {role!r}"
            )
        content = raw_message.get("content", "")
        if content is None:
            content = ""
        if not isinstance(content, str):
            content = json.dumps(content, ensure_ascii=False)

        message: dict[str, Any] = {"role": role, "content": content}
        reasoning = raw_message.get("reasoning_content", "")
        if reasoning is not None and not isinstance(reasoning, str):
            reasoning = json.dumps(reasoning, ensure_ascii=False)
        if reasoning:
            message["reasoning_content"] = reasoning

        tools = parse_jsonish(raw_message.get("tools"), f"message[{message_index}].tools")
        if tools:
            message["tools"] = tools
        tool_calls = parse_jsonish(
            raw_message.get("tool_calls"),
            f"message[{message_index}].tool_calls",
        )
        if tool_calls:
            message["tool_calls"] = tool_calls
        messages.append(message)

    if not any(message["role"] == "assistant" for message in messages):
        raise ValueError("conversation contains no assistant turn")
    return messages


def is_tool_conversation(messages: Sequence[Mapping[str, Any]]) -> bool:
    """Return whether regenerating answers could invalidate a tool trajectory."""

    return any(
        message.get("role") == "tool"
        or bool(message.get("tools"))
        or bool(message.get("tool_calls"))
        for message in messages
    )


def clean_teacher_text(text: str) -> tuple[str, str]:
    """Split Qwen's optional ``<think>`` block from its final answer."""

    cleaned = text.strip()
    for token in QWEN_SPECIAL_TOKENS:
        cleaned = cleaned.replace(token, "")
    cleaned = cleaned.strip()

    match = re.match(
        r"^\s*<think>\s*(.*?)\s*</think>\s*(.*)$",
        cleaned,
        flags=re.DOTALL,
    )
    if match:
        reasoning = match.group(1).strip()
        content = match.group(2).strip()
    else:
        reasoning = ""
        content = cleaned.replace("<think>", "").replace("</think>", "").strip()

    if not content:
        raise ValueError("teacher generated an empty final answer")
    return reasoning, content


def output_message(message: Mapping[str, Any]) -> dict[str, Any]:
    """Copy only fields understood by the miniLLM SFT data pipeline."""

    result: dict[str, Any] = {
        "role": str(message["role"]),
        "content": str(message.get("content", "")),
    }
    if message.get("reasoning_content"):
        result["reasoning_content"] = str(message["reasoning_content"])
    if message.get("tools"):
        # Existing SFT Arrow features store optional structured fields as JSON
        # strings.  Keep that convention in newly generated files.
        result["tools"] = json.dumps(message["tools"], ensure_ascii=False)
    if message.get("tool_calls"):
        result["tool_calls"] = json.dumps(
            message["tool_calls"], ensure_ascii=False
        )
    return result


def teacher_context_message(message: Mapping[str, Any]) -> dict[str, str]:
    """Convert a non-tool miniLLM message to Qwen's chat input format."""

    return {
        "role": str(message["role"]),
        "content": str(message.get("content", "")),
    }


@dataclass
class ConversationState:
    """Mutable state used to batch the same assistant turn across source rows."""

    source_index: int
    messages: list[dict[str, Any]]
    cursor: int = 0
    assistant_index: int = 0
    output_messages: list[dict[str, Any]] = field(default_factory=list)
    teacher_messages: list[dict[str, str]] = field(default_factory=list)

    def advance_to_assistant(self) -> bool:
        """Copy context messages and stop immediately before an assistant turn."""

        while self.cursor < len(self.messages):
            message = self.messages[self.cursor]
            if message["role"] == "assistant":
                return True
            self.output_messages.append(output_message(message))
            self.teacher_messages.append(teacher_context_message(message))
            self.cursor += 1
        return False

    def add_teacher_answer(self, reasoning: str, content: str) -> None:
        message: dict[str, Any] = {"role": "assistant", "content": content}
        if reasoning:
            message["reasoning_content"] = reasoning
        self.output_messages.append(message)
        # Previous hidden reasoning is not needed to answer a later user turn.
        self.teacher_messages.append({"role": "assistant", "content": content})
        self.cursor += 1
        self.assistant_index += 1

    @property
    def complete(self) -> bool:
        return self.cursor >= len(self.messages)


class TeacherGenerator:
    """Small wrapper around Hugging Face generation with lazy heavy imports."""

    def __init__(self, args: argparse.Namespace) -> None:
        try:
            import torch
            from transformers import AutoModelForCausalLM, AutoTokenizer
        except ImportError as exc:
            raise RuntimeError(
                "Teacher generation requires torch and transformers. "
                "Install the project requirements first."
            ) from exc

        self.torch = torch
        self.args = args
        self.device = self._resolve_device(args.device)
        self.dtype = self._resolve_dtype(args.dtype)
        torch.manual_seed(args.seed)
        if torch.cuda.is_available():
            torch.cuda.manual_seed_all(args.seed)

        print(f"Loading teacher : {args.model_path}")
        print(f"Teacher device  : {self.device}")
        print(f"Teacher dtype   : {str(self.dtype).removeprefix('torch.')}")
        self.tokenizer = AutoTokenizer.from_pretrained(
            args.model_path,
            use_fast=True,
            local_files_only=args.local_files_only,
            trust_remote_code=args.trust_remote_code,
        )
        if self.tokenizer.pad_token_id is None:
            self.tokenizer.pad_token = self.tokenizer.eos_token
        self.tokenizer.padding_side = "left"
        self.tokenizer.truncation_side = "left"

        self.model = AutoModelForCausalLM.from_pretrained(
            args.model_path,
            torch_dtype=self.dtype,
            local_files_only=args.local_files_only,
            trust_remote_code=args.trust_remote_code,
        )
        self.model.to(self.device)
        self.model.eval()
        self.model.requires_grad_(False)
        self.model.config.use_cache = True

    def _resolve_device(self, requested: str):
        torch = self.torch
        if requested != "auto":
            device = torch.device(requested)
        elif torch.cuda.is_available():
            device = torch.device("cuda")
        elif getattr(torch.backends, "mps", None) and torch.backends.mps.is_available():
            device = torch.device("mps")
        else:
            device = torch.device("cpu")
        if device.type == "cuda" and not torch.cuda.is_available():
            raise RuntimeError("CUDA was requested but is unavailable")
        return device

    def _resolve_dtype(self, requested: str):
        torch = self.torch
        if requested == "float32":
            return torch.float32
        if requested == "float16":
            return torch.float16
        if requested == "bfloat16":
            return torch.bfloat16
        if self.device.type == "cuda":
            return (
                torch.bfloat16
                if torch.cuda.is_bf16_supported()
                else torch.float16
            )
        if self.device.type == "mps":
            return torch.float16
        return torch.float32

    def generate(
        self,
        conversations: Sequence[Sequence[Mapping[str, str]]],
        *,
        thinking: bool,
    ) -> list[tuple[str, str]]:
        """Generate one assistant response for each conversation prefix."""

        if not conversations:
            return []
        tokenizer = self.tokenizer
        prompts = [
            tokenizer.apply_chat_template(
                list(messages),
                tokenize=False,
                add_generation_prompt=True,
                enable_thinking=thinking,
            )
            for messages in conversations
        ]
        encoded = tokenizer(
            prompts,
            add_special_tokens=False,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=self.args.max_prompt_tokens,
        )
        encoded = {key: value.to(self.device) for key, value in encoded.items()}
        prompt_width = encoded["input_ids"].shape[1]
        temperature = (
            self.args.thinking_temperature
            if thinking
            else self.args.temperature
        )
        top_p = self.args.thinking_top_p if thinking else self.args.top_p

        with self.torch.inference_mode():
            generated = self.model.generate(
                **encoded,
                max_new_tokens=self.args.max_new_tokens,
                do_sample=True,
                temperature=temperature,
                top_p=top_p,
                top_k=self.args.top_k,
                repetition_penalty=self.args.repetition_penalty,
                pad_token_id=tokenizer.pad_token_id,
                eos_token_id=tokenizer.eos_token_id,
                use_cache=True,
            )
        answers: list[tuple[str, str]] = []
        for sequence in generated:
            text = tokenizer.decode(
                sequence[prompt_width:],
                skip_special_tokens=False,
                clean_up_tokenization_spaces=False,
            )
            answers.append(clean_teacher_text(text))
        return answers


def distill_states(
    states: Sequence[ConversationState],
    generator: TeacherGenerator,
    *,
    seed: int,
    thinking_ratio: float,
) -> None:
    """Regenerate every assistant turn, batching states at the same turn depth."""

    active = list(states)
    while active:
        ready = [state for state in active if state.advance_to_assistant()]
        active = [state for state in ready if not state.complete]
        if not active:
            break

        for thinking in (False, True):
            group = [
                state
                for state in active
                if (
                    stable_probability(
                        seed,
                        state.source_index,
                        f"thinking:{state.assistant_index}",
                    )
                    < thinking_ratio
                )
                == thinking
            ]
            if not group:
                continue
            answers = generator.generate(
                [state.teacher_messages for state in group],
                thinking=thinking,
            )
            if len(answers) != len(group):
                raise RuntimeError("teacher returned an unexpected batch size")
            for state, (reasoning, content) in zip(group, answers, strict=True):
                state.add_teacher_answer(reasoning, content)


def chunked(iterable: Iterable[Any], size: int) -> Iterator[list[Any]]:
    iterator = iter(iterable)
    while chunk := list(itertools.islice(iterator, size)):
        yield chunk


def count_jsonl_rows(path: Path) -> int:
    count = 0
    with path.open("r", encoding="utf-8") as handle:
        for count, line in enumerate(handle, start=1):
            try:
                json.loads(line)
            except json.JSONDecodeError as exc:
                raise ValueError(
                    f"cannot resume: invalid JSON in {path} line {count}: {exc}"
                ) from exc
    return count


def iter_source_rows(
    path: Path,
    *,
    skip_rows: int,
    max_rows: int,
) -> Iterator[tuple[int, dict[str, Any]]]:
    with path.open("r", encoding="utf-8") as handle:
        for source_index, line in enumerate(handle):
            if source_index < skip_rows:
                continue
            if max_rows and source_index >= skip_rows + max_rows:
                break
            try:
                row = json.loads(line)
            except json.JSONDecodeError as exc:
                raise ValueError(
                    f"invalid source JSON in {path} line {source_index + 1}: {exc}"
                ) from exc
            if not isinstance(row, dict):
                raise TypeError(f"source line {source_index + 1} must be an object")
            yield source_index, row


def atomic_write_json(path: Path, value: Mapping[str, Any]) -> None:
    temporary = path.with_name(path.name + ".tmp")
    temporary.write_text(
        json.dumps(value, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    os.replace(temporary, path)


def manifest_config(args: argparse.Namespace) -> dict[str, Any]:
    return {
        "input_path": str(args.input_path),
        "output_path": str(args.output_path),
        "model_path": args.model_path,
        "start_index": args.start_index,
        "batch_size": args.batch_size,
        "distill_ratio": args.distill_ratio,
        "thinking_ratio": args.thinking_ratio,
        "max_prompt_tokens": args.max_prompt_tokens,
        "max_new_tokens": args.max_new_tokens,
        "seed": args.seed,
        "device": args.device,
        "dtype": args.dtype,
        "temperature": args.temperature,
        "top_p": args.top_p,
        "thinking_temperature": args.thinking_temperature,
        "thinking_top_p": args.thinking_top_p,
        "top_k": args.top_k,
        "repetition_penalty": args.repetition_penalty,
        "tool_policy": args.tool_policy,
    }


def verify_resume_manifest(path: Path, expected: Mapping[str, Any]) -> None:
    if not path.is_file():
        return
    current = json.loads(path.read_text(encoding="utf-8"))
    recorded = current.get("config", {})
    mismatches = [
        key
        for key, expected_value in expected.items()
        if recorded.get(key) != expected_value
    ]
    if mismatches:
        raise ValueError(
            "resume configuration differs from the existing manifest: "
            + ", ".join(mismatches)
        )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate mixed black-box distillation SFT data with Qwen3."
    )
    parser.add_argument("--input-path", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output-path", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--model-path", default="Qwen/Qwen3-1.7B")
    parser.add_argument("--batch-size", type=int, default=4)
    parser.add_argument(
        "--distill-ratio",
        type=float,
        default=0.7,
        help="Fraction of non-tool rows whose assistant turns are regenerated.",
    )
    parser.add_argument(
        "--thinking-ratio",
        type=float,
        default=0.15,
        help="Fraction of regenerated assistant turns using Qwen thinking mode.",
    )
    parser.add_argument("--max-prompt-tokens", type=int, default=1024)
    parser.add_argument("--max-new-tokens", type=int, default=384)
    parser.add_argument("--max-samples", type=int, default=0)
    parser.add_argument("--start-index", type=int, default=0)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--device", default="auto")
    parser.add_argument(
        "--dtype",
        choices=["auto", "bfloat16", "float16", "float32"],
        default="auto",
    )
    parser.add_argument("--temperature", type=float, default=0.7)
    parser.add_argument("--top-p", type=float, default=0.8)
    parser.add_argument("--thinking-temperature", type=float, default=0.6)
    parser.add_argument("--thinking-top-p", type=float, default=0.95)
    parser.add_argument("--top-k", type=int, default=20)
    parser.add_argument("--repetition-penalty", type=float, default=1.05)
    parser.add_argument(
        "--tool-policy",
        choices=["preserve"],
        default="preserve",
        help="Tool trajectories are preserved to keep calls and results consistent.",
    )
    parser.add_argument("--resume", action="store_true")
    parser.add_argument("--local-files-only", action="store_true")
    parser.add_argument("--trust-remote-code", action="store_true")
    parser.add_argument("--log-interval", type=int, default=100)
    return parser.parse_args()


def validate_args(args: argparse.Namespace) -> None:
    args.input_path = project_path(args.input_path)
    args.output_path = project_path(args.output_path)
    if not args.input_path.is_file():
        raise FileNotFoundError(f"source SFT file not found: {args.input_path}")
    if args.input_path == args.output_path:
        raise ValueError("--output-path must differ from --input-path")
    if args.batch_size <= 0 or args.log_interval <= 0:
        raise ValueError("--batch-size and --log-interval must be positive")
    if args.max_prompt_tokens <= 0 or args.max_new_tokens <= 0:
        raise ValueError("token limits must be positive")
    if args.max_samples < 0 or args.start_index < 0:
        raise ValueError("sample limits cannot be negative")
    if not 0.0 <= args.distill_ratio <= 1.0:
        raise ValueError("--distill-ratio must be in [0, 1]")
    if not 0.0 <= args.thinking_ratio <= 1.0:
        raise ValueError("--thinking-ratio must be in [0, 1]")
    if args.temperature <= 0 or args.thinking_temperature <= 0:
        raise ValueError("temperatures must be positive")
    if not 0.0 < args.top_p <= 1.0 or not 0.0 < args.thinking_top_p <= 1.0:
        raise ValueError("top-p values must be in (0, 1]")
    if args.top_k <= 0 or args.repetition_penalty <= 0:
        raise ValueError("--top-k and --repetition-penalty must be positive")


def main() -> None:
    args = parse_args()
    validate_args(args)
    random.seed(args.seed)

    args.output_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path = args.output_path.with_suffix(args.output_path.suffix + ".manifest.json")
    config = manifest_config(args)
    completed_rows = 0
    previous_stats: Mapping[str, Any] = {}
    previous_elapsed = 0.0
    if args.output_path.exists():
        if not args.resume:
            raise FileExistsError(
                f"output already exists: {args.output_path}; pass --resume to continue"
            )
        verify_resume_manifest(manifest_path, config)
        completed_rows = count_jsonl_rows(args.output_path)
        if manifest_path.is_file():
            previous_manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
            previous_stats = previous_manifest.get("stats", {})
            previous_elapsed = float(previous_manifest.get("elapsed_seconds", 0.0))

    remaining = 0 if not args.max_samples else max(0, args.max_samples - completed_rows)
    if args.max_samples and remaining == 0:
        print(f"Already completed requested {args.max_samples:,} rows.")
        return

    source_skip = args.start_index + completed_rows
    source_rows = iter_source_rows(
        args.input_path,
        skip_rows=source_skip,
        max_rows=remaining,
    )

    # Avoid allocating the teacher when a zero distill ratio is intentionally
    # used to validate streaming/resume behavior.
    generator = TeacherGenerator(args) if args.distill_ratio > 0 else None
    mode = "a" if completed_rows else "w"
    stats = {
        "processed_rows": completed_rows,
        "distilled_rows": int(previous_stats.get("distilled_rows", 0)),
        "replay_rows": int(previous_stats.get("replay_rows", 0)),
        "preserved_tool_rows": int(previous_stats.get("preserved_tool_rows", 0)),
        "assistant_turns_generated": int(
            previous_stats.get("assistant_turns_generated", 0)
        ),
    }
    started = time.perf_counter()

    with args.output_path.open(mode, encoding="utf-8") as output_handle:
        for batch in chunked(source_rows, args.batch_size):
            ordered_results: dict[int, dict[str, Any]] = {}
            states: list[ConversationState] = []
            for source_index, row in batch:
                try:
                    messages = normalize_messages(row.get("conversations"))
                except Exception as exc:
                    raise ValueError(
                        f"invalid source conversation at line {source_index + 1}: {exc}"
                    ) from exc

                if is_tool_conversation(messages):
                    ordered_results[source_index] = {
                        "conversations": [output_message(message) for message in messages]
                    }
                    stats["preserved_tool_rows"] += 1
                elif stable_probability(
                    args.seed, source_index, "distill-row"
                ) >= args.distill_ratio:
                    ordered_results[source_index] = {
                        "conversations": [output_message(message) for message in messages]
                    }
                    stats["replay_rows"] += 1
                else:
                    states.append(ConversationState(source_index, messages))

            if states:
                if generator is None:
                    raise RuntimeError("teacher generator was not initialized")
                distill_states(
                    states,
                    generator,
                    seed=args.seed,
                    thinking_ratio=args.thinking_ratio,
                )
                for state in states:
                    if not state.complete:
                        raise RuntimeError(
                            f"row {state.source_index + 1} was not fully generated"
                        )
                    ordered_results[state.source_index] = {
                        "conversations": state.output_messages
                    }
                    stats["distilled_rows"] += 1
                    stats["assistant_turns_generated"] += state.assistant_index

            for source_index, _ in batch:
                output_handle.write(
                    json.dumps(
                        ordered_results[source_index],
                        ensure_ascii=False,
                        separators=(",", ":"),
                    )
                    + "\n"
                )
            output_handle.flush()
            stats["processed_rows"] += len(batch)

            manifest = {
                "status": "running",
                "config": config,
                "stats": stats,
                "elapsed_seconds": round(
                    previous_elapsed + time.perf_counter() - started, 3
                ),
            }
            atomic_write_json(manifest_path, manifest)
            if (
                stats["processed_rows"] % args.log_interval < len(batch)
                or (args.max_samples and stats["processed_rows"] >= args.max_samples)
            ):
                elapsed = max(time.perf_counter() - started, 1e-6)
                newly_processed = stats["processed_rows"] - completed_rows
                print(
                    f"rows={stats['processed_rows']:,} "
                    f"distilled={stats['distilled_rows']:,} "
                    f"replay={stats['replay_rows']:,} "
                    f"tools={stats['preserved_tool_rows']:,} "
                    f"rate={newly_processed / elapsed:.2f} rows/s"
                )

    final_manifest = {
        "status": "complete",
        "config": config,
        "stats": stats,
        "elapsed_seconds": round(
            previous_elapsed + time.perf_counter() - started, 3
        ),
    }
    atomic_write_json(manifest_path, final_manifest)
    print(f"Distilled data : {args.output_path}")
    print(f"Manifest       : {manifest_path}")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("Interrupted; completed JSONL rows can be resumed with --resume.", file=sys.stderr)
        raise SystemExit(130)
